### ISSUE TITLE
VS version

### ISSUE THREAD

**Issue by fatroze2000** [imarius/dc-statelesshosting#1]
Hi
I cann't open it in VS2015.
How can I open it?

**Comment by imarius** [comment]
This is written using Visual Studio Code. It uses .NET Core 1.1.1, hence the missing .sln file. You should be able to compile it using VS Code or Visual Studio 2017.

Visual Studio 2015 supports only .NET Core <= 1.1

See https://stackoverflow.com/questions/42337211/asp-net-core-support-in-visual-studio-2015 .
